defaults: &defaults
  username: postgres
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5433
  pool: 5

development: &development
  database: data_batcher_development
  <<: *defaults

test:
  database: data_batcher_test
  <<: *defaults

production:
  database: data_batcher_production
  <<: *defaults
